Conform to did:peer:2 spec
aviarytech/did-peer pull request #3
Opened 2023-11-16 19:53 UTC by frostyfrog

I ran into an issue with the [universal resolver](https://uniresolver.io) in which it was unable to resolve `did:peer:2` dids which contained multiple service blocks. I tracked the issue down to the regex check in this library and when I brought it up with @dbluhm, it was recommended that I make other fixes while I was already fixing the service issue. With recent clarifications and fixes to the [did:peer numalgo 2 spec](https://identity.foundation/peer-did-method-spec/index.html#method-2-multiple-inception-key-without-doc), the appropriate clarifications have been applied to this spec.

2023-11-16 20:03 UTC, dbluhm commented
Relevant PR to Peer DID Method spec: https://github.com/decentralized-identity/peer-did-method-spec/pull/62
FWIW, these changes look good to me!

2023-11-27 15:29 UTC, TheTechmage commented
Just a slight nudge in case this issue slipped through your notifications, @brianorwhatever

2023-11-27 17:48 UTC, brianorwhatever commented
oh thanks @frostyfrog totally missed this in my queue. thanks for the nudge will take a look today!

2023-11-27 18:24 UTC, brianorwhatever requested changes
@frostyfrog this looks good for the most part the main thing I'd like to see changed is the absolute vs relative `id` properties. Really we should be using absolute `id` values for the service blocks as well as this is currently not valid JSON-LD but I think it's ok to leave them as relative as that is how that they were originally.

2023-11-27 18:24 UTC, brianorwhatever commented on src/lib/resolve.ts
> +                    id: `#key-${keyIndex++}`,
I prefer absolute URIs over relative. I know the spec uses relative and these get quite ugly but I don't think it will matter at an interoperability level unless I'm missing something

2023-11-27 18:24 UTC, brianorwhatever commented on src/lib/resolve.ts
> +                    type: 'Multikey',
Cool to use new Data Integrity suites. I need to update my other libraries but will pin versions if I can't get to updating them as this is the right path forward

2023-11-27 18:24 UTC, brianorwhatever commented on src/lib/utils.ts
> +        if (metadata.index == 0) {
```suggestion
        if (metadata.index === 0) {
```

2023-11-27 18:24 UTC, brianorwhatever commented on src/lib/utils.ts
> +    services: IDIDDocumentServiceDescriptor[],
```suggestion
    services: IDIDDocumentServiceDescriptor[]
```

2023-11-27 18:24 UTC, brianorwhatever commented on src/lib/utils.ts
> +    if (didPeerNumalgo < 2) {
did:peer:2 doesn't have `capabilityDelegation` or `capabilityInvocation`?

2023-11-27 18:24 UTC, brianorwhatever commented on src/tests/fixtures/peerdid-python/numalgo2-diddoc.json
> +			"id": "a-very-unique-service",
```suggestion
			"id": "#a-very-unique-service",
```

2023-11-28 15:09 UTC, dbluhm commented on src/lib/resolve.ts
> +                    id: `#key-${keyIndex++}`,
I believe you're correct; whether the URLs are "expanded" or left as relative should not significantly impact interop as either should be considered acceptable. Using absolute URIs here I think is fair. @frostyfrog

2023-11-28 15:14 UTC, dbluhm commented on src/lib/utils.ts
> +    if (didPeerNumalgo < 2) {
did:peer:2 does support expressing `capabilityDelegation` and `capabilityInvocation` but, unfortunately, only as an explicitly marked value; for instance: `.Dz6Mkj3PUd1WjvaDhNZhhhXQdz5UnZXmS7ehtx8bsPpD47kKc` will cause the key with multikey material `z6Mkj3PUd1WjvaDhNZhhhXQdz5UnZXmS7ehtx8bsPpD47kKc` to be added to the verification method list and a reference added to `capabilityDelegation` but not into any other verification relationship.

It is because of limitations like these that we're moving to [did:peer:4](https://identity.foundation/peer-did-method-spec/index.html#method-4-short-form-and-long-form) which can express any DID Document without limitations.

2023-11-28 17:05 UTC, brianorwhatever commented on src/lib/resolve.ts
> +                    id: `#key-${keyIndex++}`,
Alternatively I'd be ok with using relative and putting an `"@base": "did:peer:2z123najb..." in the `@context` which will effectively do the same thing

2023-12-04 18:19 UTC, frostyfrog commented on src/lib/resolve.ts
> +                    id: `#key-${keyIndex++}`,
I like the idea of using `@base` as it allows the document to be a bit cleaner when a Human is reading it. I have added it to the context property according to the pattern demonstrated in [example 150](https://www.w3.org/TR/json-ld11/#example-150-linked-data-dataset) in the JSON-LD docs.

2023-12-04 18:22 UTC, frostyfrog commented on src/lib/utils.ts
> +    if (didPeerNumalgo < 2) {
I'm not sure what needs to be done here as Delegation and Invocation are foreign diddoc concepts to me. All of my recent work has revolved around `.E` and `.V`. I've only seen references to `.I` and `.D` and I've never seen them used in practice.

2023-12-08 17:47 UTC, merged

2023-12-08 17:55 UTC, brianorwhatever commented
@frostyfrog I have published `@aviarytech/did-peer@0.0.24` are you able to test that this version is working as expected?

2023-12-08 18:51 UTC, frostyfrog commented
Unfortunately, I don't have any immediate way to test. I could set something up, though it would take some time to do so. As described over at https://github.com/decentralized-identity/peer-did-method-spec/issues/64, there were 4 other apps/libs that need updating before https://dev.uniresolver.io/ would start working (which is where I first discovered the issue). For all I know, they might just grab the change or they might each need to be rebuilt and updated.

I'll take a look into what needs to happen in order to test that things are working when I have a spare moment.